import { Router } from "express";
import webhookRoutes from "./webhook.routes";
import jobsRoutes from "./jobs.routes";
import metricsRoutes from "./metrics.routes";
import authRoutes from "./auth.routes";
import adsIntelligenceRoutes from "./ads-intelligence.routes";
import adsDraftRoutes from "./ads-drafts.routes";
import integrationHubRoutes from "./integration-hub.routes";
import companiesRoutes from './companies.routes';
import companySignupRoutes from './company-signup.routes';
import companyOnboardingRoutes from './company-onboarding.routes';

const router = Router();
router.use("/webhook", webhookRoutes);
router.use("/jobs", jobsRoutes);
router.use("/metrics", metricsRoutes);
router.use("/auth", authRoutes);
router.use("/ai", adsIntelligenceRoutes);
router.use("/ai", adsDraftRoutes);
router.use("/integrations", integrationHubRoutes);
router.use('/companies', companiesRoutes);
router.use('/company-signup', companySignupRoutes);
router.use('/company-onboarding', companyOnboardingRoutes);
export default router;
