/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AcceptInviteRouteImport } from './routes/accept-invite'
import { Route as AiAdsRouteImport } from './routes/ai-ads'
import { Route as CreativesRouteImport } from './routes/creatives'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as JobsRouteImport } from './routes/jobs'
import { Route as LoginRouteImport } from './routes/login'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as SubscriptionsRouteImport } from './routes/subscriptions'
import { Route as ViolationsRouteImport } from './routes/violations'
import { Route as CampaignsCampaignIdRouteImport } from './routes/campaigns.$campaignId'
import { Route as ManageIndexRouteImport } from './routes/manage.index'
import { Route as ManageCampaignIdRouteImport } from './routes/manage.$campaignId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AcceptInviteRoute = AcceptInviteRouteImport.update({
  id: '/accept-invite',
  path: '/accept-invite',
  getParentRoute: () => rootRouteImport,
} as any)
const AiAdsRoute = AiAdsRouteImport.update({
  id: '/ai-ads',
  path: '/ai-ads',
  getParentRoute: () => rootRouteImport,
} as any)
const CreativesRoute = CreativesRouteImport.update({
  id: '/creatives',
  path: '/creatives',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const JobsRoute = JobsRouteImport.update({
  id: '/jobs',
  path: '/jobs',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const SubscriptionsRoute = SubscriptionsRouteImport.update({
  id: '/subscriptions',
  path: '/subscriptions',
  getParentRoute: () => rootRouteImport,
} as any)
const ViolationsRoute = ViolationsRouteImport.update({
  id: '/violations',
  path: '/violations',
  getParentRoute: () => rootRouteImport,
} as any)
const CampaignsCampaignIdRoute = CampaignsCampaignIdRouteImport.update({
  id: '/campaigns/$campaignId',
  path: '/campaigns/$campaignId',
  getParentRoute: () => rootRouteImport,
} as any)
const ManageIndexRoute = ManageIndexRouteImport.update({
  id: '/manage/',
  path: '/manage/',
  getParentRoute: () => rootRouteImport,
} as any)
const ManageCampaignIdRoute = ManageCampaignIdRouteImport.update({
  id: '/manage/$campaignId',
  path: '/manage/$campaignId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/accept-invite': typeof AcceptInviteRoute
  '/ai-ads': typeof AiAdsRoute
  '/creatives': typeof CreativesRoute
  '/dashboard': typeof DashboardRoute
  '/jobs': typeof JobsRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/subscriptions': typeof SubscriptionsRoute
  '/violations': typeof ViolationsRoute
  '/campaigns/$campaignId': typeof CampaignsCampaignIdRoute
  '/manage/$campaignId': typeof ManageCampaignIdRoute
  '/manage/': typeof ManageIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/accept-invite': typeof AcceptInviteRoute
  '/ai-ads': typeof AiAdsRoute
  '/creatives': typeof CreativesRoute
  '/dashboard': typeof DashboardRoute
  '/jobs': typeof JobsRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/subscriptions': typeof SubscriptionsRoute
  '/violations': typeof ViolationsRoute
  '/campaigns/$campaignId': typeof CampaignsCampaignIdRoute
  '/manage/$campaignId': typeof ManageCampaignIdRoute
  '/manage': typeof ManageIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/accept-invite': typeof AcceptInviteRoute
  '/ai-ads': typeof AiAdsRoute
  '/creatives': typeof CreativesRoute
  '/dashboard': typeof DashboardRoute
  '/jobs': typeof JobsRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/subscriptions': typeof SubscriptionsRoute
  '/violations': typeof ViolationsRoute
  '/campaigns/$campaignId': typeof CampaignsCampaignIdRoute
  '/manage/$campaignId': typeof ManageCampaignIdRoute
  '/manage/': typeof ManageIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/accept-invite'
    | '/ai-ads'
    | '/creatives'
    | '/dashboard'
    | '/jobs'
    | '/login'
    | '/register'
    | '/subscriptions'
    | '/violations'
    | '/campaigns/$campaignId'
    | '/manage/$campaignId'
    | '/manage/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/accept-invite'
    | '/ai-ads'
    | '/creatives'
    | '/dashboard'
    | '/jobs'
    | '/login'
    | '/register'
    | '/subscriptions'
    | '/violations'
    | '/campaigns/$campaignId'
    | '/manage/$campaignId'
    | '/manage'
  id:
    | '__root__'
    | '/'
    | '/accept-invite'
    | '/ai-ads'
    | '/creatives'
    | '/dashboard'
    | '/jobs'
    | '/login'
    | '/register'
    | '/subscriptions'
    | '/violations'
    | '/campaigns/$campaignId'
    | '/manage/$campaignId'
    | '/manage/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AcceptInviteRoute: typeof AcceptInviteRoute
  AiAdsRoute: typeof AiAdsRoute
  CreativesRoute: typeof CreativesRoute
  DashboardRoute: typeof DashboardRoute
  JobsRoute: typeof JobsRoute
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  SubscriptionsRoute: typeof SubscriptionsRoute
  ViolationsRoute: typeof ViolationsRoute
  CampaignsCampaignIdRoute: typeof CampaignsCampaignIdRoute
  ManageCampaignIdRoute: typeof ManageCampaignIdRoute
  ManageIndexRoute: typeof ManageIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accept-invite': {
      id: '/accept-invite'
      path: '/accept-invite'
      fullPath: '/accept-invite'
      preLoaderRoute: typeof AcceptInviteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-ads': {
      id: '/ai-ads'
      path: '/ai-ads'
      fullPath: '/ai-ads'
      preLoaderRoute: typeof AiAdsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/creatives': {
      id: '/creatives'
      path: '/creatives'
      fullPath: '/creatives'
      preLoaderRoute: typeof CreativesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jobs': {
      id: '/jobs'
      path: '/jobs'
      fullPath: '/jobs'
      preLoaderRoute: typeof JobsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/subscriptions': {
      id: '/subscriptions'
      path: '/subscriptions'
      fullPath: '/subscriptions'
      preLoaderRoute: typeof SubscriptionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/violations': {
      id: '/violations'
      path: '/violations'
      fullPath: '/violations'
      preLoaderRoute: typeof ViolationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/campaigns/$campaignId': {
      id: '/campaigns/$campaignId'
      path: '/campaigns/$campaignId'
      fullPath: '/campaigns/$campaignId'
      preLoaderRoute: typeof CampaignsCampaignIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manage/': {
      id: '/manage/'
      path: '/manage'
      fullPath: '/manage/'
      preLoaderRoute: typeof ManageIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manage/$campaignId': {
      id: '/manage/$campaignId'
      path: '/manage/$campaignId'
      fullPath: '/manage/$campaignId'
      preLoaderRoute: typeof ManageCampaignIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AcceptInviteRoute: AcceptInviteRoute,
  AiAdsRoute: AiAdsRoute,
  CreativesRoute: CreativesRoute,
  DashboardRoute: DashboardRoute,
  JobsRoute: JobsRoute,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  SubscriptionsRoute: SubscriptionsRoute,
  ViolationsRoute: ViolationsRoute,
  CampaignsCampaignIdRoute: CampaignsCampaignIdRoute,
  ManageCampaignIdRoute: ManageCampaignIdRoute,
  ManageIndexRoute: ManageIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
